---
ansible_user: "lwatson"
ansible_become_pass: "{{ _vault_ansible_become_pass }}"
docker_service_enable: false

zfs_monitoring_scrub_pools:
  - "rpool"

zfs_monitoring_trim_pools:
  - "rpool"

borgmatic_config_encryption_passphrase: "{{ _vault_borgmatic_config_encryption_passphrase }}"
borgmatic_uptime_kuma_push_url: "{{ _vault_borgmatic_uptime_kuma_push_url }}"
borgmatic_ssh_key_contents: "{{ _vault_borgmatic_ssh_key_contents }}"
borgmatic_repo_encryption: "repokey"

borgmatic_config_source_directories:
  - "/efi"
  - "/home/lwatson/.config"
  - "/home/lwatson/.local/share/weechat/logs"
  - "/home/lwatson/.ssh"
  - "/home/lwatson/documents"
  - "/home/lwatson/games"
  - "/home/lwatson/music"
  - "/home/lwatson/pictures"
  - "/var/lib/portage"

borgmatic_config_repositories:
  - path: "ssh://zh4596@zh4596.rsync.net/./borg/serenity"
    label: "rsync.net"

borgmatic_config_commands:
  - before: "action"
    when:
      - "create"
    run:
      - "/usr/local/libexec/notifications/borgmatic-notify.py start"
  - after: "action"
    when:
      - "create"
    states:
      - "finish"
    run:
      - "/usr/local/libexec/notifications/borgmatic-notify.py finish"
  - after: "error"
    when:
      - "create"
    run:
      - "/usr/local/libexec/notifications/borgmatic-notify.py error {error}"

borgmatic_service_overrides_extra:
  Service:
    - "ExecStart="
    - >-
      ExecStart=systemd-inhibit --who="borgmatic" --what="sleep:shutdown"
      --why="Prevent interrupting scheduled backup"
      /usr/bin/borgmatic --verbosity -2 --syslog-verbosity 1 --stats
    - "PrivateDevices=no"
    - "CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_RAW CAP_SYS_ADMIN"
    - "RestrictNamespaces=no"

_notifications_apprise_urls_uk:
  - url: "{{ borgmatic_uptime_kuma_push_url }}?-status=up&method=get"
    tags:
      - "borgmatic-start"
      - "borgmatic-success"
  - url: "{{ borgmatic_uptime_kuma_push_url }}?-status=down&method=get"
    tags:
      - "borgmatic-error"
