---
ansible_user: "lwatson"
docker_service_enable: false

zfs_monitoring_scrub_pools:
  - "rpool"

zfs_monitoring_trim_pools:
  - "rpool"

borgmatic_source_directories:
  - "/home/lwatson/.config"
  - "/home/lwatson/.local/share/weechat/logs"
  - "/home/lwatson/.ssh"
  - "/home/lwatson/documents"
  - "/home/lwatson/games"
  - "/home/lwatson/music"
  - "/home/lwatson/pictures"
  - "/var/lib/portage"

borgmatic_repositories:
  - path: "ssh://zh4596@zh4596.rsync.net/./borg/serenity.lwatson.dev"
    label: "rsync.net"

borgmatic_uptime_kuma:
  push_url: "{{ _borgmatic_uptime_kuma_push_url }}"
  states:
    - "start"
    - "finish"
    - "fail"

borgmatic_service_overrides_extra:
  Service:
    - "ExecStart="
    - >-
      ExecStart=systemd-inhibit --who="borgmatic" --what="sleep:shutdown"
      --why="Prevent interrupting scheduled backup"
      /usr/bin/borgmatic --verbosity -2 --syslog-verbosity 1 --stats
    - "PrivateDevices=no"
    - "CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_RAW CAP_SYS_ADMIN"
    - "RestrictNamespaces=no"
