---
systemd_cron_enabled: true
systemd_oomd_enabled: true

# systemd_journald_config:
#   - section: "Journal"
#     options:
#       Storage: "persistent"

# systemd_system_config:
#   - section: "Manager"
#     options:
#       DefaultIPAccounting: "yes"
