---
docker_install: true
docker_service_enable: true
docker_restart_on_config_change: true
docker_daemon_config:
  log-driver: "journald"
  storage-driver: "overlay2"
  log-opts:
    tag: "{{ '{{.Name}}' }}"
  features:
    buildkit: true
