---
all:
  hosts:
    serenity:
      ansible_host: "serenity.hedgehog-skate.ts.net"
    nova:
      ansible_host: "nova.hedgehog-skate.ts.net"
    monitor:
      ansible_host: "monitor.hedgehog-skate.ts.net"
    ceres:
      ansible_host: "ceres.internal.ceres.lwatson.dev"
    ceres-firewall:
      ansible_host: "firewall.internal.ceres.lwatson.dev"
    # ceres-template-debian-13-vm:
    #   ansible_host: "template-debian-13-vm.internal.ceres.lwatson.dev"
    # ceres-template-debian-13-ct:
    #   ansible_host: "template-debian-13-ct.internal.ceres.lwatson.dev"
    ceres-caddy:
      ansible_host: "caddy.internal.ceres.lwatson.dev"
    ceres-vaultwarden:
      ansible_host: "vaultwarden.internal.ceres.lwatson.dev"
    ceres-jumphost:
      ansible_host: "ceres-jumphost.hedgehog-skate.ts.net"
      ansible_user: "root"
      ansible_ssh_common_args: ""
    ceres-postgresql:
      ansible_host: "postgresql.internal.ceres.lwatson.dev"
    ceres-mqtt:
      ansible_host: "mqtt.internal.ceres.lwatson.dev"
    ceres-zigbee2mqtt:
      ansible_host: "zigbee2mqtt.internal.ceres.lwatson.dev"
    ceres-frigate:
      ansible_host: "frigate.internal.ceres.lwatson.dev"
    do-ams3-01:
      ansible_host: "do-ams3-01.hedgehog-skate.ts.net"
    luna:
      ansible_host: "luna.lwatson.dev"
    luna-rehome:
      ansible_host: "rehome.internal.luna.lwatson.dev"
    luna-media:
      ansible_host: "media.internal.luna.lwatson.dev"
    luna-cappuccino:
      ansible_host: "cappuccino.internal.luna.lwatson.dev"
    luna-gentoogram:
      ansible_host: "gentoogram.internal.luna.lwatson.dev"
    luna-gitea:
      ansible_host: "gitea.internal.luna.lwatson.dev"
    luna-znc:
      ansible_host: "znc.internal.luna.lwatson.dev"
    luna-gitea-runner-01:
      ansible_host: "gitea-runner-01.internal.luna.lwatson.dev"
    luna-gitea-runner-02:
      ansible_host: "gitea-runner-02.internal.luna.lwatson.dev"
    luna-firewall:
      ansible_host: "firewall.internal.luna.lwatson.dev"
    luna-reverse-proxy:
      ansible_host: "reverse-proxy.internal.luna.lwatson.dev"
    luna-jumphost:
      ansible_host: "luna-jumphost.hedgehog-skate.ts.net"
      ansible_user: "root"
      ansible_ssh_common_args: ""
    # luna-template-debian-13-vm:
    #   ansible_host: "template-debian-13-vm.internal.luna.lwatson.dev"
    # luna-template-debian-13-ct:
    #   ansible_host: "template-debian-13-ct.internal.luna.lwatson.dev"
  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        ceres:
        do-ams3-01:
        monitor:
    hypervisors:
      hosts:
        ceres:
    vms:
      hosts:
        ceres-firewall:
        ceres-frigate:
        ceres-vaultwarden:
        ceres-zigbee2mqtt:
        ceres-jumphost:
        do-ams3-01:
        monitor:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
        luna-reverse-proxy:
        luna-jumphost:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
        ceres:
    gentoo:
      hosts:
        serenity:
        nova:
    debian:
      hosts:
        ceres-firewall:
        ceres:
        ceres-caddy:
        ceres-vaultwarden:
        ceres-postgresql:
        ceres-mqtt:
        ceres-zigbee2mqtt:
        ceres-frigate:
        ceres-jumphost:
        do-ams3-01:
        monitor:
        luna:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
        luna-reverse-proxy:
        luna-jumphost:
    lxc:
      hosts:
        ceres-caddy:
        ceres-postgresql:
        ceres-mqtt:
    ceres_guests:
      hosts:
        ceres-firewall:
        ceres-caddy:
        ceres-postgresql:
        ceres-mqtt:
        ceres-zigbee2mqtt:
        ceres-frigate:
        ceres-vaultwarden:
        ceres-jumphost:
    luna_guests:
      hosts:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
        luna-reverse-proxy:
        luna-jumphost:
    templates:
      hosts:
        # ceres-template-debian-13-vm:
        # ceres-template-debian-13-ct:
        # luna-template-debian-13-vm:
        # luna-template-debian-13-ct:
    smartmontools:
      hosts:
        serenity:
        luna:
        ceres:
    borgmatic:
      hosts:
        ceres-postgresql:
        ceres-vaultwarden:
        ceres-frigate:
        ceres-mqtt:
        ceres-zigbee2mqtt:
        ceres-caddy:
        ceres-firewall:
        ceres-jumphost:
        luna:
        ceres:
        monitor:
        serenity:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-jumphost:
        luna-reverse-proxy:
    docker:
      hosts:
        serenity:
        nova:
        monitor:
        ceres-vaultwarden:
        ceres-zigbee2mqtt:
        ceres-frigate:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
        luna-reverse-proxy:
