---
all:
  hosts:
    serenity:
      ansible_host: "serenity.hedgehog-skate.ts.net"
    nova:
      ansible_host: "nova.hedgehog-skate.ts.net"
    monitor:
      ansible_host: "monitor.hedgehog-skate.ts.net"
    pve:
      ansible_host: "pve.internal.home.lwatson.dev"
    pve-router:
      ansible_host: "pve-router.hedgehog-skate.ts.net"
      ansible_ssh_common_args: ""
    pve-caddy:
      ansible_host: "caddy.internal.home.lwatson.dev"
    pve-vaultwarden:
      ansible_host: "vaultwarden.internal.home.lwatson.dev"
    pve-postgresql:
      ansible_host: "postgresql.internal.home.lwatson.dev"
    pve-mqtt:
      ansible_host: "mqtt.internal.home.lwatson.dev"
    pve-zigbee2mqtt:
      ansible_host: "zigbee2mqtt.internal.home.lwatson.dev"
    pve-frigate:
      ansible_host: "frigate.internal.home.lwatson.dev"
    do-ams3-01:
      ansible_host: "do-ams3-01.hedgehog-skate.ts.net"
    luna:
      ansible_host: "luna.lwatson.dev"
    luna-jumphost:
      ansible_host: "jumphost.luna.lwatson.dev"
      ansible_ssh_common_args: ""
      ansible_connection: "ssh"
    luna-proxy:
      ansible_host: "proxy.internal.luna.lwatson.dev"
    luna-rehome:
      ansible_host: "rehome.internal.luna.lwatson.dev"
    luna-media:
      ansible_host: "media.internal.luna.lwatson.dev"
    luna-cappuccino:
      ansible_host: "cappuccino.internal.luna.lwatson.dev"
    luna-gentoogram:
      ansible_host: "gentoogram.internal.luna.lwatson.dev"
    luna-gitea:
      ansible_host: "gitea.internal.luna.lwatson.dev"
    luna-znc:
      ansible_host: "znc.internal.luna.lwatson.dev"
    luna-gitea-runner-01:
      ansible_host: "gitea-runner-01.internal.luna.lwatson.dev"
    luna-gitea-runner-02:
      ansible_host: "gitea-runner-02.internal.luna.lwatson.dev"
    luna-firewall:
      ansible_host: "firewall.internal.luna.lwatson.dev"
  children:
    workstations:
      hosts:
        serenity:
        nova:
    servers:
      hosts:
        luna:
        pve:
        do-ams3-01:
        monitor:
    vms:
      hosts:
        pve-frigate:
        pve-vaultwarden:
        pve-zigbee2mqtt:
        do-ams3-01:
        monitor:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
    zfs:
      hosts:
        luna:
        serenity:
        nova:
        pve:
    gentoo:
      hosts:
        serenity:
        nova:
    debian:
      hosts:
        pve:
        pve-router:
        pve-caddy:
        pve-vaultwarden:
        pve-postgresql:
        pve-mqtt:
        pve-zigbee2mqtt:
        pve-frigate:
        do-ams3-01:
        monitor:
        luna:
        luna-jumphost:
        luna-proxy:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
    lxc:
      hosts:
        pve-router:
        pve-caddy:
        pve-postgresql:
        pve-mqtt:
        luna-jumphost:
        luna-proxy:
    pve_guests:
      hosts:
        pve-router:
        pve-caddy:
        pve-postgresql:
        pve-mqtt:
        pve-zigbee2mqtt:
        pve-frigate:
        pve-vaultwarden:
    luna_guests:
      hosts:
        luna-jumphost:
        luna-proxy:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
    smartmontools:
      hosts:
        serenity:
        luna:
        pve:
    borgmatic:
      hosts:
        pve-postgresql:
        pve-vaultwarden:
        pve-frigate:
        pve-mqtt:
        pve-zigbee2mqtt:
        pve-router:
        luna:
        pve:
        monitor:
        serenity:
        luna-jumphost:
        luna-proxy:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-firewall:
    docker:
      hosts:
        # luna:
        serenity:
        nova:
        monitor:
        pve-vaultwarden:
        pve-zigbee2mqtt:
        pve-frigate:
        luna-rehome:
        luna-media:
        luna-cappuccino:
        luna-gentoogram:
        luna-gitea:
        luna-znc:
        luna-gitea-runner-01:
        luna-gitea-runner-02:
