---
zfs_monitoring_zed_notify_verbose: false
zfs_monitoring_zed_notify_interval_secs: 3600
zfs_monitoring_zed_scrub_after_resilver: false
zfs_monitoring_zed_email_addr: "none"
zfs_monitoring_zed_extra: {}

zfs_monitoring_install_timers: true
zfs_monitoring_scrub_schedule: "weekly"
zfs_monitoring_scrub_pools: []
zfs_monitoring_trim_schedule: "weekly"
zfs_monitoring_trim_pools: []
