---
systemd_network_files:
  - filename: "00-ens18.network"
    config:
      - section: "Match"
        options:
          Name: "ens18"
      - section: "Network"
        options:
          DHCP: "yes"
      - section: "Route"
        options:
          Destination: "100.64.0.0/10"
          Gateway: "10.10.0.1"
  - filename: "01-ens19.network"
    config:
      - section: "Match"
        options:
          Name: "ens19"
      - section: "Network"
        options:
          DHCP: "no"
          Address:
            - "2001:1b40:5000:51:dead:babe:0:1/64"
            - "2001:1b40:5000:51:dead:babe:0:2/64"
            - "2001:1b40:5000:51:dead:babe:0:3/64"
            - "2001:1b40:5000:51:dead:babe:0:4/64"
            - "2001:1b40:5000:51:dead:babe:0:5/64"
            - "2001:1b40:5000:51:dead:babe:0:6/64"
      - section: "Route"
        options:
          Destination: "::/0"
          Gateway: "2001:1b40:5000:51::1"

borgmatic_config_source_directories:
  - "/srv/stacks/foxbnc"
