---
apt_unattended_upgrades_mail_enabled: true

borgmatic_config_source_directories:
  - "/etc/postgresql"

borgmatic_config_postgresql_databases:
  - name: "all"
    hostname: "127.0.0.1"
    username: "postgres"
    password: "{{ borgmatic_postgresql_password }}"
    format: "custom"
