---
apt_unattended_upgrades_mail_sender: "{{ msmtp_from_addr }}"

borgmatic_config_before_everything:
  - "/usr/local/libexec/notifications/borgmatic-notify.py start"

borgmatic_config_after_everything:
  - "/usr/local/libexec/notifications/borgmatic-notify.py finish"

borgmatic_config_source_directories:
  - "/srv/caddy"
  - "/srv/uptimekuma"
  - "/srv/stacks/uptimekuma"

borgmatic_config_repositories:
  - path: "ssh://zh4596@zh4596.rsync.net/./borg/monitor"
    label: "rsync.net"

borgmatic_config_sqlite_databases:
  - path: "/srv/uptimekuma/data/kuma.db"
    name: "kuma"

_notifications_apprise_urls_uk:
  - url: "{{ borgmatic_uptime_kuma_push_url }}?-status=up&method=get"
    tags:
      - "borgmatic-start"
      - "borgmatic-success"
  - url: "{{ borgmatic_uptime_kuma_push_url }}?-status=down&method=get"
    tags:
      - "borgmatic-error"
