---
systemd_network_files: []
systemd_network_resolved_enabled: true
systemd_network_resolved_configure: true
systemd_network_configure: true
systemd_network_resolved_options: {}
systemd_network_networkd_configure: false
systemd_network_networkd_config: []
