---
- name: "zfs-monitoring:install:packages"
  ansible.builtin.package:
    name: "{{ __zfs_monitoring_packages[ansible_facts['os_family']] }}"
  when: "ansible_facts['os_family'] in __zfs_monitoring_packages"

- name: "zfs-monitoring:install:scripts"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/zfs/zed.d/{{ item | basename | splitext | first }}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_fileglob:
    - "{{ role_path }}/templates/*.sh.j2"
  notify: "zfs-zed:restart"

- name: "zfs-monitoring:configure:zed.rc"
  ansible.builtin.template:
    src: "templates/zed.rc.j2"
    dest: "/etc/zfs/zed.d/zed.rc"
    owner: "root"
    group: "root"
    mode: "0640"
  notify: "zfs-zed:restart"

- name: "zfs-monitoring:timers:install"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename | splitext | first }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_fileglob:
    - "{{ role_path }}/templates/systemd/*.j2"
  when: "zfs_monitoring_install_timers"

- name: "zfs-monitoring:timers:enable:scrub"
  ansible.builtin.systemd:
    name: "zfs-scrub@{{ item }}.timer"
    state: "started"
    enabled: true
    daemon_reload: true
  loop: "{{ zfs_monitoring_scrub_pools }}"
  when: "zfs_monitoring_install_timers"

- name: "zfs-monitoring:timers:enable:trim"
  ansible.builtin.systemd:
    name: "zfs-trim@{{ item }}.timer"
    state: "started"
    enabled: true
    daemon_reload: true
  loop: "{{ zfs_monitoring_trim_pools }}"
  when: "zfs_monitoring_install_timers"
