---
apt_unattended_upgrades_mail_enabled: true

systemd_network_networkd_configure: true
systemd_network_networkd_config:
  - section: "Network"
    options:
      IPv4Forwarding: "yes"
      IPv6Forwarding: "yes"

systemd_network_files:
  - filename: "00-ens18.network"
    config:
      - section: "Match"
        options:
          Name: "ens18"
      - section: "Network"
        options:
          Address: "192.168.68.56/22"
          Gateway: "192.168.68.1"
          DNS: "127.0.0.1"
          IPv6AcceptRA: "no"
  - filename: "01-ens19.network"
    config:
      - section: "Match"
        options:
          Name: "ens19"
      - section: "Network"
        options:
          Address: "10.10.10.1/24"
          IPv6AcceptRA: "no"
          DNS: "127.0.0.1"
          Domains: "internal.ceres.lwatson.dev"
