---
systemd_network_files:
  - filename: "00-ens18.network"
    config:
      - section: "Match"
        options:
          Name: "ens18"
      - section: "Network"
        options:
          DHCP: "yes"
      - section: "DHCP"
        options:
          UseDomains: "yes"
  - filename: "01-ens19.network"
    config:
      - section: "Match"
        options:
          Name: "ens19"
      - section: "Network"
        options:
          DHCP: "ipv4"
      - section: "DHCP"
        options:
          UseGateway: "false"
          UseRoutes: "false"
          UseDNS: "false"
          UseDomains: "false"

users:
  - name: "root"
    ssh_keys: "{{ _lwatson_ssh_keys + [_ansible_public_key] }}"

  - name: "lwatson"
    password: "{{ _vault_users_lwatson_pass }}"
    ssh_keys: "{{ _lwatson_ssh_keys }}"
