---
borgmatic_config_source_directories:
  - "/srv/zigbee2mqtt"
  - "/srv/stacks/zigbee2mqtt"

borgmatic_config_sqlite_databases:
  - path: "/srv/zigbee2mqtt/data/database.db"
    name: "zigbee2mqtt"
