---
apt_unattended_upgrades_mail_enabled: true

systemd_network_files:
  - filename: "00-ens18.network"
    sections:
      - name: "Match"
        settings:
          Name: "ens18"
      - name: "Network"
        settings:
          Address: "109.169.11.131/29"
          Gateway: "109.169.11.129"
          DNS: "127.0.0.1"
  - filename: "01-ens19.network"
    sections:
      - name: "Match"
        settings:
          Name: "ens19"
      - name: "Network"
        settings:
          Address: "10.10.0.1/24"
