---
- name: "uv:checkexists"
  ansible.builtin.stat:
    path: "{{ __uv_bin_dir }}/uv"
  register: "__uv_exists_result"
  tags: ["uv"]

- name: "uv:installer:download"
  ansible.builtin.get_url:
    url: "https://astral.sh/uv/install.sh"
    dest: "{{ __uv_installer_download_dest }}"
    mode: "0755"
  when: "not __uv_exists_result.stat.exists"
  changed_when: false
  tags: ["uv"]

- name: "uv:installer:run"
  environment:
    INSTALLER_NO_MODIFY_PATH: "1"
    UV_INSTALL_DIR: "{{ __uv_bin_dir }}"
  ansible.builtin.command:
    cmd: "{{ __uv_installer_download_dest }}"
    creates: "{{ __uv_bin_dir }}/uv"
  changed_when: false
  tags: ["uv"]
