---
# Short self-test daily at 02:00, long self-test Sundays at 02:00
smartmontools_schedule: "S/../.././02|L/../../7/02"

systemd_network_configure: false
systemd_network_resolved_options:
  DNSSEC: "allow-downgrade"
  DNSOverTLS: "opportunistic"

users:
  - name: "root"
    password: "{{ _vault_users_root_pass }}"
    ssh_keys: "{{ _lwatson_ssh_keys + [_ansible_public_key] }}"

  - name: "lwatson"
    password: "{{ _vault_users_lwatson_pass }}"
    linger: true
    ssh_keys: "{{ _lwatson_ssh_keys }}"
    sudo: true
