---
common_packages:
  - "app-shells/bash-completion"
  - "net-dns/bind-tools"
  - "app-misc/ca-certificates"
  - "net-misc/curl"
  - "dev-vcs/git"
  - "app-crypt/gnupg"
  - "sys-process/htop"
  - "app-misc/jq"
  - "net-libs/ldns"
  - "net-analyzer/mtr"
  - "sys-apps/net-tools"
  - "sys-process/psmisc"
  - "dev-debug/strace"
  - "app-admin/sudo"
  - "net-analyzer/tcpdump"
  - "app-misc/tmux"
  - "app-editors/vim"
