---
zfs_monitoring_scrub_schedule: "weekly"
zfs_monitoring_trim_schedule: "weekly"

zfs_monitoring_telegram_bot_token: "{{ _vault_zfs_monitoring_telegram_bot_token }}"

_notifications_apprise_urls_zfs:
  - url: "tgram://{{ zfs_monitoring_telegram_bot_token }}/{{ telegram_chat_id }}"
    tags:
      - "zfs-error-html"
      - "zfs-warning-html"
      - "zfs-ok-html"

borgmatic_service_overrides_extra:
  Service:
    - "ExecStart="
    - >-
      ExecStart=systemd-inhibit --who="borgmatic" --what="sleep:shutdown"
      --why="Prevent interrupting scheduled backup"
      /usr/bin/borgmatic --verbosity -2 --syslog-verbosity 1 --stats
    - "PrivateDevices=no"
    - "CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_RAW CAP_SYS_ADMIN"
