---
- name: "common:profile:xdg_dirs"
  ansible.builtin.template:
    src: "etc/profile.d/xdg.sh"
    dest: "/etc/profile.d/xdg.sh"
    mode: "0644"
  tags: ["common"]

- name: "common:apt:no-recommends"
  ansible.builtin.template:
    src: "etc/apt/apt.conf.d/99ansible-no-recommends.j2"
    dest: "/etc/apt/apt.conf.d/99ansible-no-recommends"
    mode: "0644"
  when: "ansible_facts['os_family'] == 'Debian'"
  tags: ["common"]

- name: "common:packages:install"
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: "present"
  when: "common_packages | length > 0"
  tags: ["common"]
