---
systemd_network_files:
  - filename: "00-eth0.network"
    config:
      - section: "Match"
        options:
          Name: "eth0"
      - section: "Network"
        options:
          DHCP: "yes"
      - section: "DHCP"
        options:
          UseDomains: "yes"
      - section: "Route"
        options:
          Destination: "100.64.0.0/10"
          Gateway: "10.10.10.1"
