---
__sysctl_file: "/etc/sysctl.d/90-ansible.conf"

__sysctl_base_vars:
  - name: "net.ipv6.route.max_size"
    value: 65000
    comment: "https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861115"

  - name: "kernel.core_pattern"
    value: "/dev/null"
