---
- name: "docker:conflicts:remove"
  ansible.builtin.package:
    name: "{{ __docker_conflicting_packages[ansible_facts['os_family']] }}"
    state: "absent"
  when: "ansible_facts['os_family'] in __docker_conflicting_packages"
  tags: ["docker"]

- name: "docker:apt:keyrings_dir:create"
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: "directory"
    mode: "0755"
  when: "ansible_facts['os_family'] == 'Debian'"
  tags: ["docker"]

- name: "docker:apt:gpg_key:download"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"
  when: "ansible_facts['os_family'] == 'Debian'"
  tags: ["docker"]

- name: "docker:apt:repository:add"
  ansible.builtin.deb822_repository:
    name: "docker"
    types: "deb"
    uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: "stable"
    architectures: "{{ __docker_arch_map[ansible_facts['architecture']] }}"
    signed_by: "/etc/apt/keyrings/docker.asc"
    state: "present"
  when: "ansible_facts['os_family'] == 'Debian'"
  tags: ["docker"]

- name: "docker:apt:update"
  ansible.builtin.apt:
    update_cache: true
  when: "ansible_facts['os_family'] == 'Debian'"
  tags: ["docker"]

- name: "docker:packages:install"
  ansible.builtin.package:
    name: "{{ __docker_packages[ansible_facts['os_family']] }}"
    state: "present"
  when: "ansible_facts['os_family'] in __docker_packages"
  tags: ["docker"]

- name: "docker:socket:enable"
  ansible.builtin.service:
    name: "docker.socket"
    enabled: true
  when: "ansible_facts['os_family'] in __docker_packages"
  tags: ["docker"]

- name: "docker:service:configure"
  ansible.builtin.service:
    name: "docker"
    state: "{{ 'started' if docker_service_enable else 'stopped' }}"
    enabled: "{{ docker_service_enable }}"
  when: "ansible_facts['os_family'] in __docker_packages"
  tags: ["docker"]
