---
ansible_ssh_common_args: "-o ProxyJump={{ hostvars['ceres-jumphost'].ansible_user }}@{{ hostvars['ceres-jumphost'].ansible_host }}"
ansible_ssh_pass: "{{ _vault_ansible_ssh_pass }}"

systemd_network_resolved_configure: true
systemd_network_resolved_options:
  Cache: "no"

systemd_network_files:
  - filename: "00-ens18.network"
    sections:
      - name: "Match"
        settings:
          Name: "ens18"
      - name: "Network"
        settings:
          DHCP: "yes"
      - name: "DHCP"
        settings:
          UseDomains: "yes"
      - name: "Route"
        settings:
          Destination: "100.64.0.0/10"
          Gateway: "10.10.10.1"

users:
  - name: "root"
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINsAsuoVftyoaDix0RovWc4vr7JcC6VBptAcxBj58P8j lwatson@serenity"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHGF/qUoS5O+MqtE+1T0fkjWNHLfBG7MYWTeQPg3G86o lwatson@nova"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGfepV156UKrBujA0FY+8NSVvEYg4N9s+l69Cb43K0Fz lwatson@reaver"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID9+0Z+T9LCRa54gB1oXTIzc82R5J7IS2QLZcy4nIJLI u0_a329@localhost"
      - "{{ _ansible_public_key }}"

borgmatic_config_encryption_passphrase: "{{ _vault_borgmatic_config_encryption_passphrase }}"
borgmatic_ssh_key_contents: "{{ _vault_borgmatic_ssh_key_contents }}"

_notifications_apprise_urls_borgmatic:
  - url: "tgram://{{ borgmatic_telegram_bot_token }}/{{ telegram_chat_id }}"
    tags:
      - "borgmatic-error-html"

borgmatic_config_repositories:
  - path: "ssh://zh4596@zh4596.rsync.net/./borg/ceres-guests/{{ ansible_facts['hostname'] }}"
    label: "rsync.net"

borgmatic_config_keep_monthly: 0
borgmatic_config_relocated_repo_access_is_ok: true
