---
- name: "Apply common configuration"
  hosts: "all"
  roles:
    - "common"
    - "systemd"

- name: "Apply sysctl configuration"
  hosts: "all,!lxc"
  roles:
    - "sysctl"

- name: "Apply docker daemon configuration"
  hosts: "docker"
  roles:
    - "docker"

- name: "Set up zram"
  hosts: "all,!lxc"
  roles:
    - "zram"

- name: "Set up apt unattended-upgrades and listchanges"
  hosts: "debian"
  roles:
    - "apt-unattended-upgrades"

- name: "Set up needrestart"
  hosts: "all"
  roles:
    - "needrestart"

- name: "Set up msmtp"
  hosts: "debian"
  roles:
    - "msmtp"

- name: "Set up SMART disk monitoring"
  hosts: "all,!lxc,!vms,!nova"
  roles:
    - "smartmontools"

- name: "Set up notification tools"
  hosts: "debian"
  roles:
    - "uv"
    - "telegram-send"

- name: "Set up ZFS monitoring"
  hosts: "zfs"
  roles:
    - "zfs-monitoring"
