---
- name: "Manage users"
  hosts: "all"
  roles:
    - "users"

- name: "Apply common configuration"
  hosts: "all"
  roles:
    - "common"
    - "systemd"

- name: "Apply sysctl configuration"
  hosts: "all,!lxc"
  roles:
    - "sysctl"

- name: "Apply networking configuration"
  hosts: "all,!hypervisors"
  roles:
    - "systemd-network"

- name: "Apply docker daemon configuration"
  hosts: "docker"
  roles:
    - "docker"

- name: "Set up zram"
  hosts: "all,!lxc"
  roles:
    - "zram"

- name: "Configure apt"
  hosts: "debian"
  roles:
    - "apt"

- name: "Set up needrestart"
  hosts: "all"
  roles:
    - "needrestart"

- name: "Set up msmtp"
  hosts: "debian"
  roles:
    - "msmtp"

- name: "Set up S.M.A.R.T. disk monitoring"
  hosts: "all,!lxc,!vms,!nova"
  roles:
    - "smartmontools"

- name: "Set up notifications"
  hosts: "borgmatic:zfs"
  roles:
    - "notifications"

- name: "Set up ZFS monitoring"
  hosts: "zfs"
  roles:
    - "zfs-monitoring"

- name: "Apply SSH configuration"
  hosts: "all,!workstations"
  roles:
    - "ssh"

- name: "Set up borgmatic backups"
  hosts: "borgmatic"
  roles:
    - "borgmatic"
