---
- name: "systemd-network:resolved|restart"
  ansible.builtin.service:
    name: "systemd-resolved"
    enabled: true
    state: "restarted"

- name: "systemd-network:systemd:daemon-reload"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "systemd-network:networkd:reload"
  ansible.builtin.systemd:
    name: "systemd-networkd"
    state: "reloaded"
