---
name: "Lint"

on: # yamllint disable-line rule:truthy
  - "push"
  - "pull_request"

env:
  UV_FROZEN: 1

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          submodules: true

      - name: "Install uv"
        uses: "astral-sh/setup-uv@v7"
        with:
          enable-cache: true
          cache-python: true

      - name: "Install Python dependencies"
        run: "uv sync --group dev"

      - name: "Lint"
        uses: "j178/prek-action@v2"
        with:
          extra-args: "--all-files"
